### PR TITLE
Remove node_modules

### PR DESCRIPTION
**Pull request by russellbanks**
It's generally bad practice to commit `node_modules`. The `package.json` and `package-lock.json` at the root of the project is enough.

`node_modules` is also in the [.gitignore](https://github.com/Minionguyjpro/Inno-Setup-Action/blob/main/.gitignore)

### CODE REVIEW

**Comment by Minionguyjpro** [comment]
> It's generally bad practice to commit `node_modules`. The `package.json` and `package-lock.json` at the root of the project is enough.
> 
> `node_modules` is also in the [.gitignore](https://github.com/Minionguyjpro/Inno-Setup-Action/blob/main/.gitignore)

I just thought about this, but in this case it is not handy to remove it. It is because the @actions/core dependency is required for it to function, and it isn't handy for the user to install it themselves.

**Comment by russellbanks** [comment]
@Minionguyjpro, see the GitHub [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) for this specifically:

> Checking in your node_modules directory can cause problems. As an alternative, you can use a tool called [@vercel/ncc](https://github.com/vercel/ncc) to compile your code and modules into one file used for distribution.

You should use [@vercel/ncc](https://github.com/vercel/ncc) to avoid committing node_modules

**Comment by Minionguyjpro** [comment]
> @Minionguyjpro, see the GitHub [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) for this specifically:
> 
> > Checking in your node_modules directory can cause problems. As an alternative, you can use a tool called [@vercel/ncc](https://github.com/vercel/ncc) to compile your code and modules into one file used for distribution.
> 
> You should use [@vercel/ncc](https://github.com/vercel/ncc) to avoid committing node_modules

How would I be able to integrate thos with GitHub Actions and the marketplace? I don't need a final file or something, just so that it can be pushed to GitHub Actions' marketplace.

**Comment by russellbanks** [comment]
I don't maintain any actions myself, so I'm not well versed with this. However, this is the way that pretty much all actions go about avoiding node_modules. For example, [@actions/checkout](https://github.com/actions/checkout) has [`@vercel/ncc`](https://github.com/vercel/ncc) in their [package.json](https://github.com/actions/checkout/blob/b4ffde65f46336ab88eb53be808477a3936bae11/package.json#L44).

The GitHub [documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) for this should work:

> Checking in your `node_modules` directory can cause problems. As an alternative, you can use a tool called [`@vercel/ncc`](https://github.com/vercel/ncc) to compile your code and modules into one file used for distribution.
> 1. Install `vercel/ncc` by running this command in your terminal.
`npm i -g @vercel/ncc`
> 2. Compile your `index.js` file.
`ncc build index.js --license licenses.txt`
> 3. You'll see a new `dist/index.js` file with your code and the compiled modules. You will also see an accompanying `dist/licenses.txt` file containing all the licenses of the `node_modules` you are using.
> 4. Change the `main` keyword in your `action.yml` file to use the new `dist/index.js` file.
`main: 'dist/index.js'`
> 5. If you already checked in your `node_modules` directory, remove it.
`rm -rf node_modules/*`
> 6. From your terminal, commit the updates to your `action.yml`, `dist/index.js`, and `node_modules` files.

**Comment by Minionguyjpro** [comment]
I see. Though I'm not sure whether it integrates well with Dependabot and automatic updates.

**Comment by Minionguyjpro** [comment]
@russellbanks I think I begin to understand how this works. I am tinkering a bit around now with some stuff, like automation and begin to understand that I need my main JavaScript file in the ``src`` folder and the ``dist`` folder will only contain the final ``index.js`` file with the modules and final code embedded into it.

**Pull request merged**
